### ISSUE TITLE
Discussion: Bash-it Alias/Plugin/Completion Load Priority

### ISSUE THREAD

**Issue by nwinkler** [Bash-it/bash-it#944]
# Work in Progress

Sorry for the long post...

The work on this feature can be tracked in the [load-priority branch in my Bash-it fork](https://github.com/nwinkler/bash-it/tree/load-priority) for the first part, and the [enabled-global branch](https://github.com/nwinkler/bash-it/tree/enabled-global) for the second half. I will create a pull request on the main Bash-it repo once the implementation has been completed (see #974 for the first half and #1043 for the second half).

Please feel free to provide comments on this feature - especially @tswicegood, @edubxb, @revans and @thedrow. Others are of course welcome, too.

# Problem Statement

One recurring problem (see #688 and #841 for examples) has been that Bash-it loads its components in a predefined order and does not allow to define dependencies between the components.

The fixed order for loading the components is

* aliases
* plugins
* completions

This leads to the following problems, with two different flavors:

* Within the same kind (e.g. plugins), load order is determined by alphabetical order, which means that the `node` plugin is loaded before the `nvm` plugin. When using `nvm` to install and run Node.js, `nvm` needs to be loaded first to make the `node` command available. With the current load order of Bash-it, this is not possible.
* Dependencies between different kinds of components do not work. One example is the `alias-completion` plugin, which tries to enable shell completions for aliases. Since plugins are loaded before completions, the plugin does not find any completions that it could apply to the defined aliases. The current fix for this is to either move the plugin to the `custom` folder, or to run `reload` after Bash-it has loaded.

There are probably more examples than these two.

# Solution Approach

The approach described here tries to address the two main problems described above.

## Load Order

(Implemented in #974)

To address the problem with a load order that's not purely based on the component's name, we are going to introduce a numeric value that determines the order in which the files are loaded.

With the current approach, the component (e.g. the `nvm` plugin) is linked into the `plugins/enabled` folder as `nvm.plugin.bash`. To break up the dependency on the plugin name for load order, a three digit numeric value will be introduced when creating the link, e.g `250---nvm.plugin.bash`.

Using a format like this for the link will allow to tailor the order of loading the files since the order will be based on the numeric value instead of the name, and the three dashes will allow to parse the name, separating the number from the name of the plugin.

By default, each type of component will have a default priority, preventing us from having to update all of the files:

* Aliases: `150`
* Plugins: `250`
* Completions: `350`

These values allow for adjusting individual components up or down. To specify a different load priority for a component, we will introduce an optional comment value in the component file, which allows to override the default priority:

```bash
# BASH_IT_LOAD_PRIORITY: 999
```

If this value is found in a component's file while enabling the component, it will be used instead of the default priority.

To implement this, the following areas of Bash-it have to be touched:

* Enable Component will need to parse the component file and then create the link in the new format.
* Show Components will need to parse the name of the links in the `enabled` folder to display which ones are enabled.
* Disable Components will need to find the component to disable.

This solves the first problem by allowing to specify that the `nvm` plugin should be loaded before the `node` plugin:

* The `nvm` plugin uses a custom priority, with a lower value than the default for plugins, e.g. `225`.
* The `node` plugin uses the default priority of `250`.

If both are enabled, it will look like this:

* `225---nvm.plugin.bash`
* `250---node.plugin.bash`

## One Common "Enabled" Directory

(Implemented in #1043)

The second problem of having a predefined order of the different component types (first aliases, then plugins, then completions), is caused by the fact that each of the components has their own `enabled` directory, which is then loaded in turn by the `bash_it.sh` script.

To break up this fixed order, we are going to introduce a common `enabled` directory that will replace the individual directories. It's going to be placed at `$BASH_IT/enabled`

Same as above the Enable, Show and Disable functionalities will have to be adjusted to make this work, using the common directory instead of the individual ones.

There should not be any naming conflicts, since the component files use an individual extension, e.g. `.plugin.bash` for plugins.

### Backwards-Compatibility

To allow existing installations to work, the common `enabled` directory will be loaded before the current loop that loads aliases, plugins and completions. Existing installations that do not yet use the common directory will continue to work without any changes, while installations that already use the common directory will also work once all of the components have been migrated to the common directory.

### Migration

We will add a `bash-it migrate` command that moves the symbolic links of the enabled components from the individual directories to the new common directory.

In addition to this, the `migrate` command will automatically run whenever the user enables a new component. This will ensure that existing installations will continue to work without changes, but once the user enables new functionality, the existing components will be migrated.

The `migrate` command will display a message to tell the user how many items were migrated to the new common `enabled` directory.

# Tasks

I'm probably going to commit this a two separate Pull Requests, where the first one will introduce the load priority, but still use the individual directories, and then the second one will move everything into a common `enabled` directory.

Some of the tasks that I'm aware of - I'll try to provide unit tests where they make sense:

# Load Order

(Implemented in #974)

- [x] `bash-it enable` a single component
- [x] `bash-it enable` all components
- [x] `bash-it disable` a single component
- [x] `bash-it disable` all components
- [x] Install script (it uses its own enabling code)
- [x] Completion needs to consider the new and the old syntax
- [x] Add `bash-it migrate` command
- [x] Automatically run `bash-it migrate` when enabling/disabling something
- [x] Update help/documentation
- [x] Fix usage of `enabled` directory in existing code, e.g. plugins and themes
- [x] Merge code (#974)

# One Common "Enabled" Directory

(Implemented in #1043)

- [x] `bash-it enable` a single component
- [x] `bash-it enable` all components
- [x] `bash-it disable` a single component
- [x] `bash-it disable` all components
- [x] Install script (it uses its own enabling code)
- [x] Completion needs to consider the new and the old location
- [x] Update `bash-it migrate` command to move enabled components to the new common directory
- [x] Automatically run `bash-it migrate` when enabling/disabling something
- [x] Update help/documentation
- [x] Update the `bash_it.sh` code to load the global `enabled` directory's content
- [x] Move/refactor/test the `command_exist` function so that there is no hidden dependency from the main code on this function from the `base` plugin. (Fixes #1009)
- [x] Merge code (#1043)

**Comment by nwinkler** [comment]
I'm probably going to commit this a two separate Pull Requests, where the first one will introduce the load priority, but still use the individual directories, and then the second one will move everything into a common `enabled` directory.

Some of the tasks that I'm aware of - I'll try to provide unit tests where they make sense:

# Load Order

- [ ] `bash-it enable` a single component
- [ ] `bash-it enable` all components
- [ ] `bash-it disable` a single component
- [ ] `bash-it disable` all components
- [ ] Install script (it uses its own enabling code)
- [ ] Completion needs to consider the new and the old syntax
- [ ] Add `bash-it migrate` command
- [ ] Update help/documentation

# One Common "Enabled" Directory

- [ ] `bash-it enable` a single component
- [ ] `bash-it enable` all components
- [ ] `bash-it disable` a single component
- [ ] `bash-it disable` all components
- [ ] Install script (it uses its own enabling code)
- [ ] Completion needs to consider the new and the old location
- [ ] Update `bash-it migrate` command to move enabled components to the new common directory
- [ ] Automatically run `bash-it migrate` when enabling something
- [ ] Update help/documentation

**Comment by nwinkler** [comment]
Implemented the first part of this in #974 - please feel free to review...

**Comment by nwinkler** [comment]
Merged the first half of this in #974 - please feel free to give it a try.

**Comment by nwinkler** [comment]
Implemented the second half in #1043 - reviews welcome!

**Comment by nwinkler** [comment]
Closing since both parts have been merged in `master` now. Open a new issue if there are any issues, please.
